
FROM debian:bookworm

RUN apt update &&\
	apt install -y vsftpd &&\
	rm -fr /var/lib/apt/lists/*

RUN mkdir -p /var/run/vsftpd/empty

COPY conf/vsftpd.conf /etc/vsftpd.conf
COPY tools/ftp-init.sh /usr/local/bin/ftp-init.sh

RUN chmod +x /usr/local/bin/ftp-init.sh

EXPOSE 21

ENTRYPOINT ["/usr/local/bin/ftp-init.sh"]
