
FROM debian:bookworm
	 
RUN apt update && apt install -y redis-server &&\
	rm -fr /var/lib/list/*

COPY conf/redis.conf /etc/redis/redis.conf

EXPOSE 6379

CMD ["redis-server", "/etc/redis/redis.conf"]
